name: Evaluation

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  evaluate:
    runs-on: ubuntu-latest

    timeout-minutes: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Collect screenshots
        uses: akosdudas/ahk-action-publish-result-pr@v1
        with:
          image-extension: ".png"
          input-file: null
          github-token: "${{ secrets.GITHUB_TOKEN }}"
